name: aldamiram
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  provider: ^6.1.1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.4.1
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/icon.png
    - shorebird.yaml
